import React from 'react';
// also exported from '@storybook/react' if you can deal with breaking changes in 6.1
import { Story, Meta } from '@storybook/react/types-6-0';
import { Section } from './Section';

export default {
  title: 'Example/Section',
  component: Section
} as Meta;

export const AppSection = () => ( 
  <>
  <Section title={'Header Level 2'}><p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veritatis quas numquam facere modi quo quaerat magnam iusto, ipsam eveniet assumenda eligendi facilis blanditiis, architecto reprehenderit officia illo iste veniam dolor? Iste in rerum fuga sequi deserunt quam reprehenderit facere sit vero recusandae quaerat aut expedita voluptatem ipsum praesentium sed architecto impedit, accusantium ex rem ipsam provident. Cum necessitatibus mollitia nemo autem odit placeat sapiente repudiandae, atque quas non sunt possimus officia impedit consequuntur molestias, distinctio voluptas ullam, architecto aliquid cupiditate. Nobis magnam id eius architecto similique totam distinctio omnis voluptatibus nemo deserunt, sunt assumenda suscipit repudiandae, repellendus animi atque earum qui cum quas fugit. Nobis, illo. Delectus laboriosam culpa ullam quae, minima perferendis assumenda veritatis perspiciatis sunt labore! Ratione, eos? Cupiditate facere ab nostrum sint doloremque modi laboriosam repudiandae rem deserunt veniam voluptatum blanditiis excepturi in exercitationem eum laudantium dignissimos necessitatibus, provident, optio ut debitis labore expedita harum. Culpa, repellendus nemo. Consequatur quod id repellendus quisquam! Iusto illo optio perferendis. Eaque quisquam id harum saepe sapiente quas aliquam dolore! Hic exercitationem reiciendis nisi, possimus nobis animi magnam modi vero doloremque iusto ipsa quo dolores perferendis aut eaque quae, repellat vitae recusandae sint quidem accusamus eum minima dolor reprehenderit! Earum, est sunt rerum repellendus, adipisci aperiam quae perferendis quaerat obcaecati sit magnam suscipit ex magni, eveniet eum et fuga quo. Ab corporis excepturi nostrum qui aliquam, dolore perspiciatis molestiae cupiditate, eaque facilis voluptas labore ut reprehenderit laudantium sit dolorum laboriosam aut sequi, amet consequuntur quas a nesciunt! Dolores nemo suscipit aspernatur esse libero laudantium, nulla tenetur facilis voluptatem? Est ab illo delectus sequi dignissimos suscipit similique, aspernatur sunt ullam numquam qui id tempore quas itaque nihil labore maxime. Mollitia porro, rerum quos nostrum sit aperiam rem, alias sunt illum sed corrupti doloremque magni quasi. Ad unde, mollitia aliquid ducimus tempora consectetur?</p></Section>
  <Section title={'Header Level 3'} headingLevel={'h3'}><p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veritatis quas numquam facere modi quo quaerat magnam iusto, ipsam eveniet assumenda eligendi facilis blanditiis, architecto reprehenderit officia illo iste veniam dolor? Iste in rerum fuga sequi deserunt quam reprehenderit facere sit vero recusandae quaerat aut expedita voluptatem ipsum praesentium sed architecto impedit, accusantium ex rem ipsam provident. Cum necessitatibus mollitia nemo autem odit placeat sapiente repudiandae, atque quas non sunt possimus officia impedit consequuntur molestias, distinctio voluptas ullam, architecto aliquid cupiditate. Nobis magnam id eius architecto similique totam distinctio omnis voluptatibus nemo deserunt, sunt assumenda suscipit repudiandae, repellendus animi atque earum qui cum quas fugit. Nobis, illo. Delectus laboriosam culpa ullam quae, minima perferendis assumenda veritatis perspiciatis sunt labore! Ratione, eos? Cupiditate facere ab nostrum sint doloremque modi laboriosam repudiandae rem deserunt veniam voluptatum blanditiis excepturi in exercitationem eum laudantium dignissimos necessitatibus, provident, optio ut debitis labore expedita harum. Culpa, repellendus nemo. Consequatur quod id repellendus quisquam! Iusto illo optio perferendis. Eaque quisquam id harum saepe sapiente quas aliquam dolore! Hic exercitationem reiciendis nisi, possimus nobis animi magnam modi vero doloremque iusto ipsa quo dolores perferendis aut eaque quae, repellat vitae recusandae sint quidem accusamus eum minima dolor reprehenderit! Earum, est sunt rerum repellendus, adipisci aperiam quae perferendis quaerat obcaecati sit magnam suscipit ex magni, eveniet eum et fuga quo. Ab corporis excepturi nostrum qui aliquam, dolore perspiciatis molestiae cupiditate, eaque facilis voluptas labore ut reprehenderit laudantium sit dolorum laboriosam aut sequi, amet consequuntur quas a nesciunt! Dolores nemo suscipit aspernatur esse libero laudantium, nulla tenetur facilis voluptatem? Est ab illo delectus sequi dignissimos suscipit similique, aspernatur sunt ullam numquam qui id tempore quas itaque nihil labore maxime. Mollitia porro, rerum quos nostrum sit aperiam rem, alias sunt illum sed corrupti doloremque magni quasi. Ad unde, mollitia aliquid ducimus tempora consectetur?</p></Section>
  <Section><p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veritatis quas numquam facere modi quo quaerat magnam iusto, ipsam eveniet assumenda eligendi facilis blanditiis, architecto reprehenderit officia illo iste veniam dolor? Iste in rerum fuga sequi deserunt quam reprehenderit facere sit vero recusandae quaerat aut expedita voluptatem ipsum praesentium sed architecto impedit, accusantium ex rem ipsam provident. Cum necessitatibus mollitia nemo autem odit placeat sapiente repudiandae, atque quas non sunt possimus officia impedit consequuntur molestias, distinctio voluptas ullam, architecto aliquid cupiditate. Nobis magnam id eius architecto similique totam distinctio omnis voluptatibus nemo deserunt, sunt assumenda suscipit repudiandae, repellendus animi atque earum qui cum quas fugit. Nobis, illo. Delectus laboriosam culpa ullam quae, minima perferendis assumenda veritatis perspiciatis sunt labore! Ratione, eos? Cupiditate facere ab nostrum sint doloremque modi laboriosam repudiandae rem deserunt veniam voluptatum blanditiis excepturi in exercitationem eum laudantium dignissimos necessitatibus, provident, optio ut debitis labore expedita harum. Culpa, repellendus nemo. Consequatur quod id repellendus quisquam! Iusto illo optio perferendis. Eaque quisquam id harum saepe sapiente quas aliquam dolore! Hic exercitationem reiciendis nisi, possimus nobis animi magnam modi vero doloremque iusto ipsa quo dolores perferendis aut eaque quae, repellat vitae recusandae sint quidem accusamus eum minima dolor reprehenderit! Earum, est sunt rerum repellendus, adipisci aperiam quae perferendis quaerat obcaecati sit magnam suscipit ex magni, eveniet eum et fuga quo. Ab corporis excepturi nostrum qui aliquam, dolore perspiciatis molestiae cupiditate, eaque facilis voluptas labore ut reprehenderit laudantium sit dolorum laboriosam aut sequi, amet consequuntur quas a nesciunt! Dolores nemo suscipit aspernatur esse libero laudantium, nulla tenetur facilis voluptatem? Est ab illo delectus sequi dignissimos suscipit similique, aspernatur sunt ullam numquam qui id tempore quas itaque nihil labore maxime. Mollitia porro, rerum quos nostrum sit aperiam rem, alias sunt illum sed corrupti doloremque magni quasi. Ad unde, mollitia aliquid ducimus tempora consectetur?</p></Section>
  </>
)
